// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: copyfrom.go

package models

import (
	"context"
)

// iteratorForCreateReports implements pgx.CopyFromSource.
type iteratorForCreateReports struct {
	rows                 []CreateReportsParams
	skippedFirstNextCall bool
}

func (r *iteratorForCreateReports) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForCreateReports) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].OccurAt,
		r.rows[0].ExternalSrcID,
		r.rows[0].Neighborhood,
		r.rows[0].LocationType,
		r.rows[0].CrimeType,
		r.rows[0].Region,
		r.rows[0].Lat,
		r.rows[0].Long,
	}, nil
}

func (r iteratorForCreateReports) Err() error {
	return nil
}

func (q *Queries) CreateReports(ctx context.Context, arg []CreateReportsParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"reports"}, []string{"occur_at", "external_src_id", "neighborhood", "location_type", "crime_type", "region", "lat", "long"}, &iteratorForCreateReports{rows: arg})
}
