// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package models

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

type CrimeType string

const (
	CrimeTypeAssault               CrimeType = "Assault"
	CrimeTypeAutoTheft             CrimeType = "Auto Theft"
	CrimeTypeTheftfromMotorVehicle CrimeType = "Theft from Motor Vehicle"
	CrimeTypeBreakandEnter         CrimeType = "Break and Enter"
	CrimeTypeSexualViolation       CrimeType = "Sexual Violation"
	CrimeTypeRobbery               CrimeType = "Robbery"
	CrimeTypeTheftOver             CrimeType = "Theft Over"
	CrimeTypeBikeTheft             CrimeType = "Bike Theft"
	CrimeTypeShooting              CrimeType = "Shooting"
	CrimeTypeHomicide              CrimeType = "Homicide"
)

func (e *CrimeType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = CrimeType(s)
	case string:
		*e = CrimeType(s)
	default:
		return fmt.Errorf("unsupported scan type for CrimeType: %T", src)
	}
	return nil
}

type NullCrimeType struct {
	CrimeType CrimeType
	Valid     bool // Valid is true if CrimeType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullCrimeType) Scan(value interface{}) error {
	if value == nil {
		ns.CrimeType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.CrimeType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullCrimeType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.CrimeType), nil
}

type Member string

const (
	MemberUSERS Member = "USERS"
)

func (e *Member) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = Member(s)
	case string:
		*e = Member(s)
	default:
		return fmt.Errorf("unsupported scan type for Member: %T", src)
	}
	return nil
}

type NullMember struct {
	Member Member
	Valid  bool // Valid is true if Member is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullMember) Scan(value interface{}) error {
	if value == nil {
		ns.Member, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.Member.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullMember) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.Member), nil
}

type Region string

const (
	RegionTORONTO Region = "TORONTO"
)

func (e *Region) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = Region(s)
	case string:
		*e = Region(s)
	default:
		return fmt.Errorf("unsupported scan type for Region: %T", src)
	}
	return nil
}

type NullRegion struct {
	Region Region
	Valid  bool // Valid is true if Region is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullRegion) Scan(value interface{}) error {
	if value == nil {
		ns.Region, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.Region.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullRegion) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.Region), nil
}

type Customer struct {
	ID               int32
	StripeCustomerID string
	UserID           pgtype.UUID
}

type Notif struct {
	ID        pgtype.UUID
	CreatedAt pgtype.Timestamptz
	IsSent    bool
	IsOpened  bool
	ScannerID int32
	UserID    pgtype.UUID
}

type Otp struct {
	ID        pgtype.UUID
	CreatedAt pgtype.Timestamptz
	ExpiresAt pgtype.Timestamptz
	IsActive  bool
	UserID    pgtype.UUID
}

type Report struct {
	ID            int32
	CreatedAt     pgtype.Timestamptz
	OccurAt       pgtype.Timestamptz
	ExternalSrcID string
	Neighborhood  pgtype.Text
	LocationType  pgtype.Text
	CrimeType     CrimeType
	Region        Region
	Point         interface{}
	Lat           float64
	Long          float64
}

type ReportNotif struct {
	CreatedAt pgtype.Timestamptz
	NotifID   pgtype.UUID
	ReportID  int32
}

type Scanner struct {
	ID        int32
	CreatedAt pgtype.Timestamptz
	IsActive  bool
	Address   pgtype.Text
	Region    Region
	Radius    float64
	Point     interface{}
	Lat       float64
	Long      float64
	UserID    pgtype.UUID
}

type Subscription struct {
	ID                   int32
	StripeSubscriptionID string
	TierID               string
	IsActive             bool
	CustomerID           int32
}

type User struct {
	ID        pgtype.UUID
	Member    Member
	CreatedAt pgtype.Timestamptz
	Email     string
}
