// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package models

import (
	"database/sql"
	"database/sql/driver"
	"fmt"
	"time"

	"github.com/google/uuid"
)

type CrimeType string

const (
	CrimeTypeAssault          CrimeType = "Assault"
	CrimeTypeAutoTheft        CrimeType = "Auto Theft"
	CrimeTypeTheftFromVehicle CrimeType = "Theft From Vehicle"
	CrimeTypeBreakAndEnter    CrimeType = "Break And Enter"
	CrimeTypeSexualViolation  CrimeType = "Sexual Violation"
	CrimeTypeRobbery          CrimeType = "Robbery"
	CrimeTypeTheftOver        CrimeType = "Theft Over"
	CrimeTypeBikeTheft        CrimeType = "Bike Theft"
	CrimeTypeShooting         CrimeType = "Shooting"
	CrimeTypeHomicide         CrimeType = "Homicide"
)

func (e *CrimeType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = CrimeType(s)
	case string:
		*e = CrimeType(s)
	default:
		return fmt.Errorf("unsupported scan type for CrimeType: %T", src)
	}
	return nil
}

type NullCrimeType struct {
	CrimeType CrimeType
	Valid     bool // Valid is true if CrimeType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullCrimeType) Scan(value interface{}) error {
	if value == nil {
		ns.CrimeType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.CrimeType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullCrimeType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.CrimeType), nil
}

type Region string

const (
	RegionTORONTO Region = "TORONTO"
)

func (e *Region) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = Region(s)
	case string:
		*e = Region(s)
	default:
		return fmt.Errorf("unsupported scan type for Region: %T", src)
	}
	return nil
}

type NullRegion struct {
	Region Region
	Valid  bool // Valid is true if Region is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullRegion) Scan(value interface{}) error {
	if value == nil {
		ns.Region, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.Region.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullRegion) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.Region), nil
}

type Notif struct {
	ID        uuid.UUID
	CreatedAt time.Time
	IsSent    bool
	IsOpened  bool
	ScannerID int32
}

type Report struct {
	ID            int32
	CreatedAt     time.Time
	OccurAt       time.Time
	ExternalSrcID string
	Neighborhood  sql.NullString
	LocationType  sql.NullString
	CrimeType     CrimeType
	Region        Region
	Point         interface{}
	Lat           float64
	Long          float64
}

type ReportNotif struct {
	CreatedAt time.Time
	NotifID   uuid.UUID
	ReportID  int32
}

type Scanner struct {
	ID        int32
	CreatedAt time.Time
	IsActive  bool
	Address   sql.NullString
	Region    Region
	Radius    float64
	Point     interface{}
	Lat       float64
	Long      float64
	UserID    int32
}

type User struct {
	ID        int32
	CreatedAt time.Time
	Email     string
}
